### PR TITLE
Make update conditional and fix perms before clearing cache.

### LINKED ISSUE #95: SELInux context sometimes incorrect after d7_update.sh runs
We originally through that this was just from `d7_migrate.sh`, but I think it's more general than that and we can see it whenever `d7_update.sh` adds code to a site on a box where SELinux is enforcing. 

That would also explain some of the intermittentcy of this problem.

### PR DESCRIPTION
**Pull request by lo5an**
* Make update process conditional on the presence of updates
* Fix permissions for drupal code when doing update 
* Clean up white space
* Clarify output and comments
* Replace `d7_update.sh` in `d7_init.sh` with `d7_cc.sh` 

Motivation and Context
----------------------
* Set correct permissions for updated modules to close #95
* General cleanup of related text UI 
* Don't check for updates immediately after core install, none will be available. 

Testing
-------------------------
- [x] No updates or permissions work when no modules are out of date.
- [x] Successful update of outdated Drupal core
- [x] Successful migration of site with out-of-date makefile and updated modules.

### CODE REVIEW

File: files/d7_init.sh [hunk 1]
```diff
@@ -139,8 +139,8 @@ sudo -u apache drush -y -r "$SITEPATH/drupal" site-install --site-name="$SITE" |
 ## Apply the apache config
 d7_httpd_conf.sh "$SITEPATH" "$SITE_TYPE" || exit 1;
 
-## Apply security updates and clear caches.
-d7_update.sh "$SITEPATH" || exit 1;
+## Clear caches.
+d7_cc.sh "$SITEPATH" || exit 1;
```
Comment (lo5an) [inline files/d7_init.sh:143]: Skipping full update, since we've just installed core.

File: files/d7_update.sh [hunk 2]
```diff
@@ -19,7 +19,16 @@ SITEPATH=$1
 
 echo "Processing $SITEPATH"
 
-## Dump DB before touching anything
+
```
Comment (lo5an) [inline files/d7_update.sh:22]: Don't do anything if no updates are available.

File: files/d7_update.sh [hunk 3]
```diff
@@ -31,12 +40,11 @@ sudo -u apache drush up -y --security-only -r "$SITEPATH/drupal"  --no-backup  |
 ## Disable update manager; no need to leave it phoning home.
 sudo -u apache drush -y dis update -r "$SITEPATH/drupal" || exit 1;
 
-## Clear the caches
+## Make sure any updated php is readable
```
Comment (lo5an) [inline files/d7_update.sh:43]: Fix perms after updating (if we got this far).

File: files/d7_update.sh [hunk 4]
```diff
@@ -31,12 +40,11 @@ sudo -u apache drush up -y --security-only -r "$SITEPATH/drupal"  --no-backup  |
...
+d7_perms.sh "$SITEPATH/drupal"
+
+## Make sure new code is loaded
 d7_cc.sh "$SITEPATH"
 
 ## Avoid a known performance-crusher in our environment
 sudo -u apache drush eval 'variable_set('drupal_http_request_fails', 0)' -r "$SITEPATH/drupal" || exit 1;
-
```
Comment (lo5an) [inline files/d7_update.sh:39]: We're fixing perms, so we don't have to set anything on this fie.

**Review by lo5an — COMMENTED** [review]
Lots of whitespace changes and comments in this PR, so I've marked the code changes in this review. 

Argh. That didn't quite work out how I'd hoped. Let me add more context.

File: files/d7_update.sh (hunk 2 above)
Comment (lo5an) [reply files/d7_update.sh:22]: I meant to call out the next few lines
```bash
+# Check for available updates
+UPDATELIST=$(drush -r "${SITEPATH}/drupal" pm-updatestatus --security-only --pipe)
+if [ "" == "${UPDATELIST}" ] ; then
+    echo "No security updates available"
+    exit 0
+fi
```

File: files/d7_update.sh (hunk 4 above)
Comment (lo5an) [reply files/d7_update.sh:39]:
```bash
-## settings.php is protected.
-sudo -u apache chmod ug=r,o= "$SITEPATH/default/settings.php" 2>/dev/null || \
-chmod ug=r,o= "$SITEPATH/default/settings.php"
```

File: files/d7_update.sh (hunk 3 above)
Comment (lo5an) [reply files/d7_update.sh:43]:
```bash
-## Clear the caches
+## Make sure any updated php is readable
+d7_perms.sh "$SITEPATH/drupal"
+
```
